### PR TITLE
added authentication and redirects for #51, and added routing commits to enhance work on #34

### PR DESCRIPTION
**Pull request by gregtuc**
Routing added on App.js in Client, and Homepage redirects to loginsignup if user is not properly signed in. JWT is used stored in the users session, and is used to get user details from server. If user clicks the sign-out button located in the navbar, the session is ended.

### CODE REVIEW

**Comment by ginywiny** [comment]
The homepage will be renamed and filled out with the part I am currently working on.

**Review by ginywiny — APPROVED** [review]
Some refactoring will be needed to support new pages Logan and I will add.

**Comment by gregtuc** [comment]
> Some refactoring will be needed to support new pages Logan and I will add.

Yup. We'll have to make sure the file names & imports have proper naming for your news feed and logans profile page

**Review by loganmcmullen — APPROVED** [review]
as michael mentioned, we'll need to tailor this code to new additions. Great work chief

**Pull request merged**
