### PR TITLE
added following users (closes #35) and follow list (closes #28)

### LINKED ISSUE #28: * Following List
As a user I would like to see a list the users that follow me so that I can see who has access to my photos and profile info at all times.

1. Create "follower" list in "profile" component
2. Send fetch request to get the list of each of user followed (backend api loop (get user.follower))
3. Front end display results

Confirmation:
Does the list update when you follow a new user? Do the changes to the list persist upon page refresh?

### LINKED ISSUE #35: * Follow Other Users
As a user I would like to be able to choose users to follow so that I can see their uploaded content.

1. Create follow button next to usernames in search results
2. API to send username using post request to appropriate route (username.following) to following user
3. API to send username using post request to appropriate route (username.follower) to followed user

Confirmation:
Is there a button to follow a user? Does the user see me as a follower? Is this user displayed as somebody I am following?

### PR DESCRIPTION
**Pull request by gregtuc**
Server: Two endpoints created for viewing all of the people who a user is following, and for adding a new follower.
Client: Added a page that displays all of the users who a person is following, and also the ability to add new users. This page uses the Navbar component and the new Following component.

### CODE REVIEW

**Review by loganmcmullen — APPROVED** [review]
All files look good. Amazing work on the following users and following list

**Review by ginywiny — APPROVED** [review]
Can use some more commenting, but overall good to go

**Review by cottonswab — COMMENTED** [review]
Why does the Travis Test fail?

**Comment by gregtuc** [comment]
> Why does the Travis Test fail?

The Travis tests are actually passing, but the Travis Build continues running afterwards and then eventually times out, causing the build to say it had failed. Either there is something wrong with Travis servers right now, or we need to double check that nothing was changed in index.js with Logans commit. Either way, the tests technically passed so integration shouldn't be a problem.

**Pull request merged**
