### PR TITLE
Base Express Server and React Server

### LINKED ISSUE #11: Set Up Server/Backend
1. Set up basic express server
2. Create two paths: signing up, searching for user
3. Connect to MongoDB

### PR DESCRIPTION
**Pull request by gregtuc**
Basic skeleton for development which includes an express and react server. In the server folder there is a basic setup for an express server (running on localhost 8000) on index.js. In index.js there is also a basic connection for the MongoDB Cloud Database. Also in the server folder is a user-schema.js file which will need to be updated to be more complex.
In the client folder there is a basic react-app. This react-app contains a folder named components which has a file named signup.js This file contains a sign-up page which can POST user login-details to the express server.

### CODE REVIEW

**Comment by MostafaEBoustani** [comment]
I believe that we should all this fork branch ? What do you guys think?

**Comment by cottonswab** [comment]
> 
> 
> I believe that we should all this fork branch ? What do you guys think?

Great idea Moustafa! Let's fork this branch.

**Comment by ma-brandonjh** [comment]
yeah we should fork the branches. It will make things easier for us

**Comment by gregtuc** [comment]
Ok yeah fork it boys

**Comment by cottonswab** [comment]
Consensus!

**Comment by loganmcmullen** [comment]
Dude dont forget to fork this PLEASE!

**Comment by cottonswab** [comment]
We will not!

**Comment by cottonswab** [comment]
Marked as to be forked by Greg.

**Comment by MostafaEBoustani** [comment]
Can we overfork a branch?

**Comment by cottonswab** [comment]
We did it!!

**Comment by ginywiny** [comment]
Users should not forget to connect to database with their own MongoDB account. Should be mentioned or automated from a sign up page

**Pull request merged**
