### PR TITLE
Added functioning Travis Test which should close #47

### LINKED ISSUE #47: Must have proper tests for login/authentication for TravisCI
Must have a test script that functions for travis CI and verifies that the login and authentication still works properly.

### PR DESCRIPTION
**Pull request by gregtuc**
Added Travis testing which can verify that user login/authentication and database connection functions correctly.

### CODE REVIEW

**Comment by gregtuc** [comment]
> Would it be possible to pre-install the server before running the scripts?

Zero clue brother

**Comment by loganmcmullen** [comment]
looks good, #merge her

**Review by loganmcmullen — APPROVED** [review]
she's beaut

**Comment by ma-brandonjh** [comment]
everything looks fine. you can merge.

**Review by cottonswab — APPROVED** [review]
changes look good

**Pull request merged**
